# Generated by Django 3.0 on 2019-12-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
