# Generated by Django 3.0 on 2019-12-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lawyer',
            field=models.CharField(default='Nil', max_length=20),
        ),
    ]
