# Generated by Django 2.2.8 on 2020-01-21 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_lawyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('caseno', models.CharField(max_length=12)),
                ('lawyer', models.CharField(default='Nil', max_length=20)),
                ('case', models.TextField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
