# Generated by Django 2.2.8 on 2020-01-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200121_1455'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='case',
            table='Case',
        ),
    ]
